### ISSUE TITLE
keithley-arduino using RS-232

### ISSUE THREAD

**Issue by ghost** [daniel-centore/keithley-617-arduino#1]
I am trying to communicate between Arduino and Keithley electrometer 6517b using RS-232 cable. 
I used an RS-232 shield for Arduino to connect it.
When I tried to communicate between Arduino and my laptop and my PC just to check whether everything was working, it just worked fine.
I used the following code on Arduino to communicate with my electrometer.
```
void setup() {
  // initialize both serial ports:
  Serial.begin(19200);//serial port on my laptop
  Serial1.begin(19200);//serial port connected to RS-232 cable
}

void loop() {
  // read from port 1, send to port 0:
  if (Serial1.available()) {
    char inByte = Serial1.read();
    Serial.write(inByte);
  }

  // read from port 0, send to port 1:
  if (Serial.available()) {
    char inByte = Serial.read();
    Serial1.write(inByte);
  }
}
```
The electrometer did not go into REM mode (i.e. Remote Operation mode).
It was not responding at all to the commands. 
Previously I was working on communicating with library using pyserial on my PC and it was working properly.

**Comment by daniel-centore** [comment]
Sorry I didn't realize you were (1) using a different electrometer with (2) a different communication method and thus (3) aren't actually using my library. I don't know what the problem is.

**Comment by ghost** [comment]
Are you able to use RS 232 with your electrometer?
